Update patcher

diff --git a/patcher b/patcher
--- a/patcher
+++ b/patcher
@@ -108,11 +108,19 @@ message warning "Attempting to defragment image! If your image is corrupted, thi
 existance "$csd/output.img" "message success 'Assembled output.img!' && cd $csd" "message error 'Failed to assemble image!' && exit 1"
 
 # Sign patched image with keyfile
-message info "Extracting public key to phh.pub.bin..."
-python3 "$csd/avbtool" extract_public_key --key "$csd/keys/phh.pem" --output "$csd/keys/phh.pub.bin" &&
-message info "Signing patched image with key..."
-python3 "$csd/avbtool" add_hash_footer --image "$csd/output.img" --partition_name recovery --partition_size "$(wc -c < "$csd/raw.img")" --key "$csd/keys/phh.pem" --algorithm SHA256_RSA4096 &&
-message success "Signed image successfully!"
+echo "extracting public key to phh.pub.bin..."
+if python3 $csd/avbtool extract_public_key --key $csd/keys/phh.pem --output $csd/keys/phh.pub.bin; then
+    echo "signing patched image with key..."
+    if python3 $csd/avbtool add_hash_footer --image $csd/output/output.img --partition_name recovery --partition_size $(wc -c $csd/raw.img | cut -f 1 -d ' ') --key $csd/keys/phh.pem --algorithm SHA256_RSA4096; then
+        echo "signed image successfully!"
+    else
+        echo "Error signing image"
+        exit 1
+    fi
+else
+    echo "Error extracting public key"
+    exit 1
+fi
 
 # Package image for use in Odin
 message info "Packaging image for Odin..."
